# Generated by Django 3.1rc1 on 2020-08-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=75),
        ),
        migrations.DeleteModel(
            name='ActivityView',
        ),
    ]
