# Generated by Django 3.1 on 2020-08-12 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20200806_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['name'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='activities.activity')),
            ],
        ),
    ]
